gameState = GameState(GlobalState().LoadGlobals())
gameState.ReadField()
gameState.ReadEntities()
gameState.ChainBombs()
gameState.PredictExplosions()
bomb_target,next_move, some = gameState.GetNewTarget(True)

print(f'Reachables {gameState.Reachable((0,0),10)}', file=sys.stderr)
print(f'Bombs {gameState.bombs}', file=sys.stderr)
print(f'Danger field {gameState.PredictExplosions()}', file=sys.stderr)
print(f'Bomb target, next_move {bomb_target},{next_move}', file=sys.stderr)