Bombs [{'owner': 1, 'x': 6, 'y': 9, 'roundsLeft': 5, 'explosionRange': 4}, {'owner': 0, 'x': 8, 'y': 2, 'roundsLeft': 6, 'explosionRange': 4}, {'owner': 2, 'x': 8, 'y': 4, 'roundsLeft': 6, 'explosionRange': 4}, {'owner': 0, 'x': 10, 'y': 2, 'roundsLeft': 6, 'explosionRange': 5}]
Danger field {(5, 9): [5], (6, 9): [5, 5], (7, 9): [5], (6, 10): [5], (8, 2): [6, 6, 6], (9, 2): [6, 6], (10, 2): [6, 6, 6], (8, 0): [6], (8, 1): [6], (8, 4): [6, 6], (9, 4): [6], (10, 4): [6, 6], (11, 4): [6], (11, 2): [6], (12, 2): [6], (10, 0): [6], (10, 1): [6], (10, 3): [6]}
Bomb target, next_move (6, 0),(10, 1)
